server:
  port: 8082

spring:
  messages:
    basename: messages/error/errorMessages
    cache-duration: -1
    encoding: UTF-8
  
  jackson:
    date-format: MM/dd/yyyy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  http:
    encoding:
      charset: UTF-8
      enabled: true
  application:
    name: order-service
    
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver


  
